-- Forced lowercase table and column names to match Entity
CREATE TABLE IF NOT EXISTS "employee"
(
    "id"         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "first_name" VARCHAR(255),
    "last_name"  VARCHAR(255),
    "status"     VARCHAR(50)
);